jobs:
  main:
    description: "Upload File via SFTP"
    tasks:
      - kind: sftp-upload
        description: Upload file via SFTP
        connection: sftp
        source: "${project.basedir}/data/example.csv"
        target: "${sftp_target}/example.csv"
        overwrite: true
