jobs:
  dump-all-years:
    description: "Dumps some records of every year"
    tasks:
      - kind: loop
        description: Loop all years between 2007 and 2014
        job: dump-single-year
        args:
          year:
            start: 2007
            end: 2014

  dump-single-year:
    description: "Dumps some records of a single year"
    parameters:
      - name: year
        type: Integer
    environment:
      - start_year=${year}
      - end_year=#set($r=$year+1)$r
    tasks:
      - kind: showEnvironment
        description: Dump current execution environment for year $start_year
      - kind: showMapping
        description: Dump measurements from year $start_year
        mapping: measurements
