config:
  - spark.hadoop.fs.s3a.endpoint=s3.eu-central-1.amazonaws.com
  - spark.hadoop.fs.s3a.access.key=<your-key>
  - spark.hadoop.fs.s3a.secret.key=<your-secret>
  - spark.hadoop.fs.s3a.proxy.host=
  - spark.hadoop.fs.s3a.proxy.port=
  - spark.hadoop.fs.s3a.proxy.username=
  - spark.hadoop.fs.s3a.proxy.password=
