name: ${plugin.name}
description: ${project.name}
version: ${plugin.version}
isolation: false
jars:
 - ${plugin.jar}
 - hbase-client-${hbase.version}.jar
 - hbase-common-${hbase.version}.jar
 - hbase-protocol-${hbase.version}.jar
 - htrace-core-3.2.0-incubating.jar
 - htrace-core4-4.0.1-incubating.jar
