name: ${plugin.name}
description: ${project.name}
version: ${plugin.version}
isolation: false
jars:
 - ${plugin.jar}
 - kafka-clients-${kafka.version}.jar
 - spark-sql-kafka-0-10_${scala.api_version}-${spark.version}.jar
